from pathlib import Path
import ast,json,hashlib,zipfile
E=Path(__file__).resolve().parents[1];B=E/'port-source/new-init-dv12-unequal-mass';R=E/'dv12-vector-review';C=R/'cpu';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();read=lambda p:json.loads(p.read_text());s=(B/'vector_screen.py').read_text()
with zipfile.ZipFile(C/'source.zip') as z:old=z.read('vector_screen.py').decode()
func=lambda x:{n.name:ast.dump(n,include_attributes=False) for n in ast.parse(x).body if isinstance(n,ast.FunctionDef)}
a,b=func(old),func(s);assert [n for n in a if a[n]!=b[n]]==['run_cuda']
assert "assert without_tensor_devices(actual_models) == without_tensor_devices(receipt['initial_material']['models'])" in s
seal=read(B/'bundle-sha256.json');assert {f.name:sha(f) for f in B.iterdir() if f.is_file() and f.name!='bundle-sha256.json'}==seal
receipt=read(C/'cpu-preflight.json');assert not (C/'executed-cpu-preflight.json').exists();(C/'executed-cpu-preflight.json').write_bytes((C/'cpu-preflight.json').read_bytes())
for name in list(receipt['source_sha256']):
 if (B/name).is_file():receipt['source_sha256'][name]=sha(B/name)
receipt['review_rebinding']={'executed_receipt_sha256':sha(C/'executed-cpu-preflight.json'),'changed_function':'run_cuda only','unchanged_cpu_construction_AST':True,'reason':'pre-update CUDA/CPU model receipt assertion only; CPU path unchanged'}
(C/'cpu-preflight.json').write_text(json.dumps(receipt,indent=2)+'\n')
review={'status':'PASS_SOURCE_AND_CPU_INITIALIZATION','bundle_sha256':sha(B/'bundle-sha256.json'),'candidate_declaration_sha256':sha(E/'port-source/api-dv12/candidate-declaration.json'),'cpu_receipt':str(C/'cpu-preflight.json'),'cpu_receipt_sha256':sha(C/'cpu-preflight.json'),'executed_cpu_receipt_sha256':sha(C/'executed-cpu-preflight.json'),'source_checks':{'ten_definitions_exact_original_archive':True,'task_and_promoted_critic_exact':True,'unchanged_candidate_package':True,'canonical_CPU_prior_first_std_point5':True,'public_initializers_before_bandwidth':True,'full_public_step_serial_default_CPU':True,'independent_cuda_streams_0_1_2':True,'all1200_dry_and_actual_data_latent_receipts':True,'all24_original_six_bound_scores_final5':True,'eval990_991_992_noise2303':True,'actualCUDA_model_comparison_required_before_updates':True},'cpu_checks':{k:receipt[k] for k in ['status','cuda_initialized','initializer_rng_neutral','repeated_without_rng_reset']},'limits':['Initialization-only: zero forwards/backwards/steps/GPU; no quality evidence.','Final runtime-only assertion seal rebind preserves original executed receipt and unchanged CPU function AST; no redundant constructor run.','CPU/GPU bandwidth reductions may differ in low bits; each must equal device-local geometry from new deterministic z.','Old2/24suffix0 unequal-massFAIL retained; only new own run may establish new result.']}
(R/'source-audit.json').write_text(json.dumps(review,indent=2)+'\n')
(R/'source-audit.md').write_text('''# DV12 unequal-mass follow-up: independent clearance\n\nSource and CPU initialization review PASS, bound to final bundle seal376eceaf47b511ef3c96eaef2f582cbe53a8b26f954bfb99aeb3ce6689d3f3a0. Ten complete model/data/scorer definitions, the original task and all six numerical bounds, and the promoted public BatchDistance critic card match the immutable DV12 old failing vector archive. Candidate package/controller/recipe policy is unchanged from the passing new-init mode-hold candidate; only256 particles/z4/batch128 host resources differ.\n\nThe guarded CPU proof constructs twice with intervening random draws and no global reset, comparing complete non-RNG state. It verifies exact std.5 R2 prior, zero batch-feature head, RNG-neutral public initialization, bandwidth derived from initialized prior and native empty Adam state. Forward/backward/optimizer steps are forbidden by sentries; CUDA remains uninitialized. A final assertion-only run_cuda change now requires every actual initialized model tensor/buffer to match the CPU proof before any update (ignoring only device labels), while bandwidth is checked against device-local deterministic geometry. The receipt is rebound to that seal with the original executed receipt retained and CPU-function AST equality verified.\n\nThe external runner preserves independentCUDA data0/latent1/penalty2, original Dreal→Dlatent→Glatent→Greal callback transaction, complete serial publicstep with defaultCPU native clocks, all1200 private dry data/latent receipts and accepted cursor checks. Frozen evaluation uses4096 samples, latent990/target991/directions992, isolated output/support stream2303 and unchanged candidate generation. All24 observations and the original final-five/six-bound gate decide quality. Initial/final source, complete state, clocks and rate/controller receipts are retained. Historical weightfixtures are provenance only; no oldweights or oldquality are loaded.\n\nThis is execution preparation only. The old2/24suffix0FAIL remains recorded; a fresh run must establish any improvement. Full proof paths and hashes are in source-audit.json.\n''')
print(json.dumps({k:review[k] for k in ['status','bundle_sha256','cpu_receipt','cpu_receipt_sha256']}))
