"""Write arms.json: the 5 x 4 no-R1 factorial on top of gs2_c03_lr2_d05 (read from ../k3p-constant-suite/arms.json)."""
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
BASE_NAME = "gs2_c03_lr2_d05"
SPIKES = {
    "none": "R1 removed, nothing added on the real side (control)",
    "symcap": "real-side one-sided RMS cap relu(||grad D(r)||/sqrt d - kappa)^2",
    "pathcap": "one-sided RMS cap at x_hat = r + u (f - r), u~U(0,1) per batch-index pair",
    "pairsec": "real-real secant cap relu((|D(r_i)-D(r_nn(i))| / ||r_i - r_nn(i)||)/sqrt d - kappa)^2, no double backprop",
    "dvalcap": "real-logit value cap relu(|D(r) - mean_batch D(r)| - 1)^2",
}
SETTLES = {
    "none": "nothing replaces R1's settling role",
    "hinge": "critic loss = relativistic hinge mean relu(1 - (D(r) - D(f))); generator keeps RpGAN softplus",
    "oadam": "critic update = lib/oadam.py OptimisticAdam(amsgrad=True), betas (0,.999), base critic LR",
    "anchor": "K3P EMA-critic anchor prox term forced on at constant LR (stock reg_anchor_weight 1, decay .999)",
}


def main():
    suite = json.loads((HERE.parent / "k3p-constant-suite" / "arms.json").read_text())["arms"]
    base = suite[BASE_NAME]
    stock_anchor_weight = 1.0  # particlegan.Recipe.reg_anchor_weight default (released K3P)
    arms = {}
    for spike, sdoc in SPIKES.items():
        for settle, tdoc in SETTLES.items():
            recipe = dict(base["recipe"])
            if settle == "anchor":
                recipe["reg_anchor_weight"] = stock_anchor_weight
            arms[f"nr_{spike}_{settle}"] = dict(
                formulation=f"{BASE_NAME} with R1 on reals removed. spike: {spdoc(spike, sdoc)}. settle: {settle}: {tdoc}. "
                            "Fake one-sided RMS cap kept; all terms (reg_coeff/2)-scaled.",
                critic="k3p", base=BASE_NAME, config=dict(base["config"]), recipe=recipe,
                nr=dict(spike=spike, settle=settle,
                        guard_buffer="max_exp_avg_sq"))
    # coefficient check: the full-suite finalists with reg_coeff 1.0 (base .3 was tuned with R1 present)
    for name in ("nr_dvalcap_anchor", "nr_none_anchor", "nr_pathcap_anchor"):
        arm = json.loads(json.dumps(arms[name]))
        arm["config"]["reg_coeff"] = 1.0
        arm["formulation"] = arm["formulation"].replace("(reg_coeff/2)-scaled", "(reg_coeff/2)-scaled, reg_coeff 1.0")
        arm["coeff_check_of"] = name
        arms[f"{name}_c1"] = arm
    doc = ("No-R1 factorial (5 spike controls x 4 settling mechanisms) on gs2_c03_lr2_d05 = k3p_simple + reg_coeff .3, "
           "lr .0085, d_lr_mult .5 (constant LR, AMSGrad (0,.999), no noise, no EMA anchor, no direct response, "
           "guard + A2 on). Every arm removes R1 on reals; every arm's spike guard reads max_exp_avg_sq (the AMSGrad buffer "
           "the update uses; the gs2 reference read exp_avg_sq). Generated by gen_arms.py.")
    (HERE / "arms.json").write_text(json.dumps({"_doc": doc, "arms": arms}, indent=1) + "\n")
    print(len(arms), "arms")
    write_e1(base)


# EMA-centred R1 (EMA_R1.md): (beta, reg_anchor_decay, reg_anchor_weight). beta 0 = gs2's R1 (identity control).
E1_GRID = [(0.0, 0.999, 1.0),                                           # control: must reproduce gs2
           (0.5, 0.999, 1.0), (0.8, 0.999, 1.0), (0.95, 0.999, 1.0), (1.0, 0.999, 1.0),  # beta sweep
           (1.0, 0.99, 1.0), (1.0, 0.9, 1.0),                            # decay at beta 1
           (1.0, 0.999, 3.0), (1.0, 0.999, 10.0)]                        # weight at beta 1


def e1_name(beta, decay, weight):
    return f"e1_b{beta:g}_d{decay:g}_w{weight:g}"


def write_e1(base):
    arms = {}
    for beta, decay, weight in E1_GRID:
        recipe = dict(base["recipe"], reg_anchor_weight=weight, reg_anchor_decay=decay)
        arms[e1_name(beta, decay, weight)] = dict(
            formulation=f"{BASE_NAME} with R1 on reals replaced by EMA-centred R1: w * mean ||grad D(r) - beta * "
                        f"grad Dbar(r)||^2 / d, beta {beta:g}, Dbar = K3P parameter-EMA critic (decay {decay:g}) "
                        f"forced on from step 0 at constant LR, w {weight:g}. Fake one-sided RMS cap unchanged; "
                        "(reg_coeff/2)-scaled. Spike guard reads exp_avg_sq as in gs2.",
            critic="k3p", base=BASE_NAME, config=dict(base["config"]), recipe=recipe,
            nr=dict(spike="none", settle="emar1", beta=beta, guard_buffer="exp_avg_sq"))
    doc = ("EMA-centred R1 family on gs2_c03_lr2_d05 (generated by gen_arms.py). beta 0 = gs2's R1 exactly; beta 1, "
           "decay .999, w 1 = nr_none_anchor's term but with gs2's guard buffer (exp_avg_sq).")
    (HERE / "arms_e1.json").write_text(json.dumps({"_doc": doc, "arms": arms}, indent=1) + "\n")
    print(len(arms), "e1 arms")


def spdoc(spike, sdoc):
    return f"{spike}: {sdoc}"


if __name__ == "__main__":
    main()
