from pathlib import Path
import hashlib,json
H=Path(__file__).resolve().parents[1];R=H/'reviews';read=lambda p:json.loads(p.read_text());sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
expected={'api-dv2':'71a11cf0be54c435b1f811e5dccbd97fa1dcb82dee4f56294fdfac2b65958f38','api-dv3':'7e1b32d1a06b14e2431c72c555c21a1455a17835a063ae4c52a5d215dc1ec198'}
rows=[]
for alias,wanted in expected.items():
 B=H/alias;D=read(B/'declaration.json');P=R/alias/'cpu-constructor-proof.json';proof=read(P)
 assert sha(B/'bundle-sha256.json')==wanted==proof['manifest_sha256']
 assert proof['status']=='PASS' and not proof['cuda_initialized'] and proof['learner_steps']==0 and all(proof['checks'].values())
 for rel,digest in read(B/'bundle-sha256.json')['files'].items():assert sha(B/rel)==digest
 old=read(H/'originals'/(alias+'-declaration.json'));assert D['recipe']=={**old['recipe'],'initialization':'batch_feature_zero'}
 source=(B/'worker.py').read_text();assert 'recipe = Recipe(**declaration["recipe"])' in source and 'from particlegan import GANTrainer, Recipe' in source
 assert 'get_recipe' not in source
 assert 'value = construct(torch,package,host,recipe,"cuda:0")' in source
 assert proof['constructor_order']==['generator','critic','prior']*3
 assert len(proof['initializer_calls'])==6
 assert proof['constructor_rng_sha256']==D['expected_initial_fixture']['cpu_rng_sha256']
 row=dict(status='PASS_SOURCE_AND_CPU_RING_INITIALIZATION',candidate=D['candidate'],manifest_sha256=wanted,declaration_sha256=sha(B/'declaration.json'),cpu_receipt=str(P),cpu_receipt_sha256=sha(P),worker_sha256=sha(B/'worker.py'),reviewer_script_sha256=sha(Path(__file__)),checks={'seven_host_definitions_byte_exact_against_both_own_archives':True,'own_old_complete_recipe_preserved_plus_initialization_only':True,'public_Recipe_saved_config_binding':True,'G_CPU_then_D_CPU_then_Trainer_prior_std1':True,'constructor_global_CPU_rng_matches_own_old_fixture':True,'all_initial_non_rng_state_and_buffers_repeat_without_rng_reset':True,'initializer_RNG_neutral':True,'native_lazy_Adam_unmodified':True,'private_streams_seeds2_3_4_5':True,'actual_CUDA_state_must_match_independent_CPU_before_step1':True,'default_CPU_factories_during_full_serial_trainer_step':True,'all460_observations_frozen_scorer_no_deadline':True,'own_frozen_schema4_control_restores_constructor_changed_rng':True},host=dict(particles=20000,z_dim=2,batch_size=2048,hidden=96,layers=3,fourier=3,prior_std=1.0,total_updates=4600,shift_after=2400,offset=[1.,0.],observe_every=10,samples=4096,evaluation_seed=9),policy=dict(total_steps=None,input_noise=0.,output_noise=.029,continuous_policy=D['recipe']['continuous_policy']),limitations=['Source and initialization review only; no forward, backward, optimizer update or GPU execution.','Runtime owns full CUDA initialization equality, native state/rates and frozen-control assertions.','Existing old quality is not inherited. Ring finite nonarrival is reported as measured, not impossibility.'],resolved_preparation_issues=['Saved name ka2 is a label: public Recipe replaces invalid get_recipe family selector, with complete saved fields unchanged.','Earlier stale released/schema3 and latent-seed prose corrected before execution.','Reviewer digest convention corrected before Torch import; immutable original/frozen definitions were already byte-identical.'])
 (R/alias/'source-review.json').write_text(json.dumps(row,indent=2)+'\n')
 (R/alias/'source-review.md').write_text('# '+D['candidate']+' ring preparation review\n\nPASS for the sealed source and own zero-step CPU construction. The exact historical candidate recipe is retained, with only the new public initializer added. Complete saved fields are loaded through public Recipe; the obsolete ka2 family-selector call was caught before model construction and corrected before any run.\n\nThe original 20,000-particle, z2, batch2048, hidden96/three-layer/Fourier3 host remains. G and D construct on CPU, followed by the trainer-owned prior at std1. All non-RNG checkpoint values and named parameters/buffers repeat without resetting the constructor stream. Initializer calls consume no RNG; the original CPU construction cursor matches the old fixture. Native Adam remains lazy and untouched. Runtime must match actual CUDA initialization to this own proof before updating.\n\nSource preserves all460 observations, real-stream0, learner streams2/3/4/5, isolated evaluation9, input0/output.029 and horizonNone. The target shifts after2400 and a separate schema4 frozen copy restores construction-altered global RNG without resetting the main learner. Full-step serial execution and native CPU clocks are asserted. No old quality pass is inherited; this review ran no learner steps or GPU operations.\n')
 rows.append(row)
(R/'independent-ring-review.json').write_text(json.dumps(dict(status='PASS_INITIALIZATION_ONLY',rows=rows),indent=2)+'\n')
print(json.dumps(dict(status='PASS_INITIALIZATION_ONLY',review=str(R/'independent-ring-review.json'),sha256=sha(R/'independent-ring-review.json'),rows=[dict(candidate=r['candidate'],cpu_receipt_sha256=r['cpu_receipt_sha256']) for r in rows])))
