from pathlib import Path
import importlib.util,json,hashlib,sys
E=Path(__file__).resolve().parents[1];B=E/'port-source/c6-retention-continuation';D=E/'port-source/late-arrival-retention';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();read=lambda p:json.loads(p.read_text())
seal=read(B/'bundle-sha256.json');assert {str(f.relative_to(B)):sha(f) for f in B.rglob('*') if f.is_file() and f.name!='bundle-sha256.json'}==seal
s=(B/'continuation.py').read_text();old=(D/'continuation.py').read_text();s=s.replace('Unchanged C6 supplementary','Unchanged DV1–DV4 supplementary').replace("assert declaration['resolved_recipe']['total_steps'] == 7000\n    assert declaration['resolved_recipe']['continuous'] is True", "assert declaration['resolved_recipe']['total_steps'] is None").replace("choices=('api-c6',)","choices=('api-dv1','api-dv2','api-dv3','api-dv4')").replace("                if hasattr(trainer, 'game_stats'):\n                    row['game_stats'] = trainer.game_stats\n",'');assert s==old
for n in ['init_contract.py','mode_hold_contract.py','preflight.py','protocol.json']:
 assert (B/n).read_bytes()==(D/n).read_bytes()
sys.path.insert(0,str(B));sp=importlib.util.spec_from_file_location('c6_continuation',B/'continuation.py');m=importlib.util.module_from_spec(sp);sp.loader.exec_module(m);plan,*_=m.source_check('api-c6')
r=importlib.util.spec_from_file_location('raw',E/'audit_public3_runtime.py');raw=importlib.util.module_from_spec(r);r.loader.exec_module(raw);final,clocks=raw.checkpoint(Path(plan['original_artifacts']['final-state.pt']['path']));assert final['trainer']['completed_steps']==1200
assert final['trainer']['recipe']['total_steps']==7000 and final['trainer']['recipe']['continuous'] is True
assert all(x==dict(step=1200.,device='cpu') for role in clocks for x in role)
a=read(E/'api-c6-runtime-audit.json');assert a['status']=='PASS'
assert 'torch' not in sys.modules
out={'status':'PASS_SOURCE_REVIEW','bundle_sha256':sha(B/'bundle-sha256.json'),'original_runtime_audit_sha256':sha(E/'api-c6-runtime-audit.json'),'original_summary':a['summary'],'original_checkpoint_sha256':plan['original_artifacts']['final-state.pt']['sha256'],'recipe':final['trainer']['recipe'],'scope':'Unchanged original C6 final1200 state through supplementary2400; no execution','limits':['Original frozen1200FAIL preserved.','Keeps original total_steps7000 continuousTrue, startupnoise360/720 and nominal rate floors1; no horizon rewriting.','Historical old-init C6 stationary collapse nearstep5030 and final7500 evidence remain separate caveats.','Uses reviewed DV1–4 restore/originalendpoint/batchcursor/serial transaction unchanged; only C6 allowlist and extra game_stats output differ.','No training/Torch import/GPU, no replay claim.']}
(E/'c6-retention-review/source-audit.json').write_text(json.dumps(out,indent=2)+'\n');(E/'c6-retention-review/source-audit.md').write_text('''# C6 supplementary retention source review\n\nPASS, bound to seal00fc76428346f0e4bdcae80cab0e971799f4d29b30ca166f345aff96cb3cda8c. The complete worker equals the reviewed DV1–DV4 continuation after reversing only its C6 label/allowlist, explicit original recipe assertions and extra game_stats logging. Full restoration, original endpoint comparison, frozen batch-cursor replay, serial public transaction, state/RNG immutability checks and24 follow-up observations remain unchanged.\n\nAll original artifact/source pins pass. The raw original1200 checkpoint has nativeCPU clocks1200 and unchanged recipe total_steps7000/continuousTrue. Startupnoise360/720 and fixed nominal LR floors1 remain; no horizon is rewritten toNone. Original frozen1200FAIL stays intact; only a separate supplementary result may be reported. Historical old-init C6 long collapse remains a limitation. No Torch import, training or GPU work was performed.\n''');print(json.dumps({k:out[k] for k in ['status','bundle_sha256','original_summary']}))
