"""Mutant definitions for pkg-E17 (review_E17_code).  Each mutant = one plausible bug injected into a COPY of pkg-E17/particlegan.
MUTANTS: list of (id, class, description, [(file, old, new), ...]); every `old` must occur exactly once in `file`.
Classes: STAT (the support statistic), PICK (the parent rule), GUARD, BOOK (bookkeeping / trainer coupling), RNG, VALID (recipe validation), DEV (dtype/device)."""
BD = 'birth_death.py'
RC = 'recipes.py'

def m(i, cls, desc, *edits):
    return (i, cls, desc, list(edits))

ARANGE = "passed = (ps <= torch.arange(1, m + 1, device=p.device, dtype=p.dtype) * self.Q / m).nonzero()"
MUTANTS = [
    # ------------------------------------------------------------------ the statistic
    m('M01', 'STAT', 'BH ranks 0-based (arange(0, m)): rank-1 threshold is 0',
      (BD, ARANGE, ARANGE.replace('arange(1, m + 1,', 'arange(0, m,'))),
    m('M02', 'STAT', 'BH ranks shifted up (arange(2, m+2)): too liberal by one rank',
      (BD, ARANGE, ARANGE.replace('arange(1, m + 1,', 'arange(2, m + 2,'))),
    m('M03', 'STAT', 'BH divides by |R2| instead of m (level doubled at even N)',
      (BD, ARANGE, ARANGE.replace('* self.Q / m)', '* self.Q / len(null))'))),
    m('M04', 'STAT', 'BH picks the FIRST passing rank (passed[0]) instead of the last',
      (BD, 'return p <= ps[int(passed[-1])]', 'return p <= ps[int(passed[0])]')),
    m('M05', 'STAT', 'calibration on the reference half itself (null = score(R1)): no split',
      (BD, 'null = score(R2).sort().values', 'null = score(R1).sort().values')),
    m('M06', 'STAT', 'calibration set overlaps the reference (R2 = whole R)',
      (BD, 'R1, R2 = R[0::2], R[1::2]', 'R1, R2 = R[0::2], R')),
    m('M07', 'STAT', 'searchsorted side flipped (right=True): ties count as smaller',
      (BD, 'torch.searchsorted(null, s)', 'torch.searchsorted(null, s, right=True)')),
    m('M08', 'STAT', 'p-value counts the wrong tail (#{null < s})',
      (BD, '(len(null) - torch.searchsorted(null, s)).double()', 'torch.searchsorted(null, s).double()')),
    m('M09', 'STAT', 'p-value without the +1 (p can be 0): anti-conservative',
      (BD, 'p = (1. + (len(null) - torch.searchsorted(null, s)).double()) / (1. + len(null))',
           'p = ((len(null) - torch.searchsorted(null, s)).double()) / (1. + len(null))')),
    m('M10', 'STAT', 'local scale: median of the k radii replaced by their mean',
      (BD, "rho[ix].sort(dim=1).values[:, (k - 1) // 2]", "rho[ix].mean(1)")),
    m('M11', 'STAT', 'local scale: upper median (index k//2) instead of lower median',
      (BD, '(k - 1) // 2', 'k // 2')),
    m('M12', 'STAT', 'rho not leave-one-out (self at distance 0 counted among the k)',
      (BD, 'rho = _knn(R1, R1, k, exclude=torch.arange(len(R1), device=R.device), shortlist_dtype=fast)[0][:, -1]',
           'rho = _knn(R1, R1, k, shortlist_dtype=fast)[0][:, -1]')),
    m('M13', 'STAT', 'rho uses the (k+1)-th neighbour (k mistaken by one)',
      (BD, 'rho = _knn(R1, R1, k, exclude=torch.arange(len(R1), device=R.device), shortlist_dtype=fast)[0][:, -1]',
           'rho = _knn(R1, R1, k + 1, exclude=torch.arange(len(R1), device=R.device), shortlist_dtype=fast)[0][:, -1]')),
    m('M14', 'STAT', 'score numerator is the nearest-neighbour distance d[:, 0] instead of the k-th',
      (BD, 'return d[:, -1] / rho[ix]', 'return d[:, 0] / rho[ix]')),
    m('M15', 'DEV', 'exact recompute in float32 (features cast to float32 at entry of _isolated)',
      (BD, 'R1, R2 = R[0::2], R[1::2]', 'q, R = q.float(), R.float()\n        R1, R2 = R[0::2], R[1::2]')),
    m('M16', 'STAT', 'no floor on the local scale (clamp_min(floor) removed): 0/0 on duplicate reservoirs',
      (BD, '.clamp_min(floor)      # the lower median', '      # the lower median')),
    m('M17', 'STAT', 'floor from the mean instead of the median of positive radii',
      (BD, 'floor = float(positive.median()) * 1e-3', 'floor = float(positive.mean()) * 1e-3')),
    m('M18', 'STAT', 'contiguous split of the reservoir (older half / newer half) instead of interleaved',
      (BD, 'R1, R2 = R[0::2], R[1::2]', 'R1, R2 = R[:len(R) // 2], R[len(R) // 2:]')),
    m('M19', 'STAT', 'flags returned inverted for the p-value threshold (p < ps[j] strict): ties at threshold dropped',
      (BD, 'return p <= ps[int(passed[-1])]', 'return p < ps[int(passed[-1])]')),
    m('M55', 'STAT', 'local scale over the k-1 nearest reference points only (nearest one dropped)',
      (BD, 'rho[ix].sort(dim=1).values[:, (k - 1) // 2]', 'rho[ix[:, 1:]].sort(dim=1).values[:, (k - 1) // 2]')),
    m('M56', 'STAT', 'floor is an absolute constant 1e-3 instead of relative to the median radius (dataset-scale dependent)',
      (BD, 'floor = float(positive.median()) * 1e-3 if len(positive) else 1.', 'floor = 1e-3')),
    m('M57', 'STAT', 'no local scale at all (score = k-th neighbour distance: the unnormalised statistic)',
      (BD, "return d[:, -1] / rho[ix].sort(dim=1).values[:, (k - 1) // 2].clamp_min(floor)", "return d[:, -1]")),
    # ------------------------------------------------------------------ integration of the statistic in maybe_apply
    m('M20', 'BOOK', 'features not centred for the support test (q + centre, R + centre)',
      (BD, 'flagged = self._isolated(q, R, k, fast) if self.isolation else None',
           'flagged = self._isolated(q + centre, R + centre, k, fast) if self.isolation else None')),
    m('M21', 'BOOK', 'reference is the fake pool F instead of the real reservoir R',
      (BD, 'flagged = self._isolated(q, R, k, fast) if self.isolation else None',
           'flagged = self._isolated(q, F, k, fast) if self.isolation else None')),
    m('M22', 'BOOK', 'k+1 passed to the support test (k mistaken by one at the call site)',
      (BD, 'flagged = self._isolated(q, R, k, fast) if self.isolation else None',
           'flagged = self._isolated(q, R, k + 1, fast) if self.isolation else None')),
    # ------------------------------------------------------------------ guard
    m('M23', 'GUARD', 'guard removed (acts whatever the flagged fraction)',
      (BD, 'acted = 0 < n_flag <= self.Q * self.N', 'acted = 0 < n_flag')),
    m('M24', 'GUARD', 'guard strict (<) instead of <= at n_flag == Q N',
      (BD, 'acted = 0 < n_flag <= self.Q * self.N', 'acted = 0 < n_flag < self.Q * self.N')),
    m('M25', 'GUARD', 'guard inverted (acts only when MORE than Q of the table is flagged)',
      (BD, 'acted = 0 < n_flag <= self.Q * self.N', 'acted = n_flag > self.Q * self.N')),
    m('M26', 'GUARD', 'guard level 10 Q (half the table) instead of Q',
      (BD, 'acted = 0 < n_flag <= self.Q * self.N', 'acted = 0 < n_flag <= 10 * self.Q * self.N')),
    m('M27', 'GUARD', 'acted / skipped counters swapped',
      (BD, 'c["iso_acted" if acted else "iso_skipped"] += bool(n_flag)', 'c["iso_skipped" if acted else "iso_acted"] += bool(n_flag)')),
    # ------------------------------------------------------------------ parent rule
    m('M28', 'PICK', 'ball factor 1 (nearest unflagged row only)',
      (BD, 'ball = dist <= 2. * dist.min(1, keepdim=True).values', 'ball = dist <= 1. * dist.min(1, keepdim=True).values')),
    m('M29', 'PICK', 'ball factor 4',
      (BD, 'ball = dist <= 2. * dist.min(1, keepdim=True).values', 'ball = dist <= 4. * dist.min(1, keepdim=True).values')),
    m('M30', 'PICK', 'ball factor applied to SQUARED distances (radius sqrt(2) x nearest)',
      (BD, 'ball = dist <= 2. * dist.min(1, keepdim=True).values', 'ball = dist.square() <= 2. * dist.min(1, keepdim=True).values.square()')),
    m('M31', 'PICK', 'min taken over the wrong axis (dim 0: nearest FLAGGED row per parent)',
      (BD, 'ball = dist <= 2. * dist.min(1, keepdim=True).values', 'ball = dist <= 2. * dist.min(0, keepdim=True).values')),
    m('M32', 'PICK', 'parents drawn among ALL rows incl. flagged ones (keep = ones)',
      (BD, 'keep = ~flagged\n', 'keep = torch.ones_like(flagged)\n')),
    m('M33', 'PICK', 'ordinary children NOT removed from the flagged set (double move of a row)',
      (BD, 'dead[child] = False', 'pass')),
    m('M34', 'PICK', 'ordinary children NOT removed from the parent set (parent = a row just moved)',
      (BD, 'keep[child] = False', 'pass')),
    m('M35', 'PICK', 'outside-of-ball rows given value 2 instead of -1 (picks a row OUTSIDE the ball)',
      (BD, 'torch.full_like(draw, -1.)', 'torch.full_like(draw, 2.)')),
    m('M36', 'PICK', 'ball computed on the EMA table instead of the live table',
      (BD, '        z = trainer.prior.z.detach()\n        parent, step', '        z = trainer.ema_prior.z.detach()\n        parent, step')),
    m('M37', 'PICK', 'chunk drops its last row (dead[start:start+step-1])',
      (BD, 'dist = torch.cdist(z[dead[start:start + step]], z[keep])', 'dist = torch.cdist(z[dead[start:start + step - 1]], z[keep])')),
    m('M38', 'PICK', 'chunk size not divided by the keep size (step = 1<<24): unbounded [chunk, keep] block',
      (BD, 'parent, step = [], max(1, (1 << 24) // len(keep))', 'parent, step = [], 1 << 24')),
    # ------------------------------------------------------------------ bookkeeping / trainer coupling
    m('M39', 'BOOK', "last['moves'] not updated (trainer neither rebases the tester nor resets evidence for iso-only moves)",
      (BD, '                last["moves"] = len(child) + len(iso_child)      # the trainer re-anchors the tester and resets the row evidence of every moved row\n', '                pass\n')),
    m('M40', 'BOOK', 'moved_rows excludes the iso rows',
      (BD, 'self.moved_rows = moved', 'self.moved_rows = child')),
    m('M41', 'BOOK', 'stale-site reset omits the iso sites',
      (BD, 'sites = torch.cat((q_loc[child], q_loc[parent], q_loc[iso_child], q_loc[iso_parent]))', 'sites = torch.cat((q_loc[child], q_loc[parent]))')),
    m('M42', 'BOOK', 'stale-site reset uses only the flagged rows old sites (parents sites omitted)',
      (BD, 'sites = torch.cat((q_loc[child], q_loc[parent], q_loc[iso_child], q_loc[iso_parent]))', 'sites = torch.cat((q_loc[child], q_loc[parent], q_loc[iso_child]))')),
    m('M43', 'BOOK', 'evidence (S, W, n) of iso rows not reset (only ordinary children)',
      (BD, 'self.S[moved] = 0.\n            self.W[moved] = 0.\n            self.n[moved] = 0', 'self.S[child] = 0.\n            self.W[child] = 0.\n            self.n[child] = 0')),
    m('M44', 'BOOK', 'EMA row not updated on iso moves',
      (BD, '        ema.z[child] = ema.z[parent] + delta\n', '        if not getattr(self, "_iso", False):\n            ema.z[child] = ema.z[parent] + delta\n'),
      (BD, '                self._move(trainer, iso_child, iso_parent)', '                self._iso = True\n                self._move(trainer, iso_child, iso_parent)\n                self._iso = False')),
    m('M45', 'BOOK', 'optimizer (Adam/AMSGrad) rows not copied on iso moves',
      (BD, 'for key, value in state.items():', 'for key, value in ({} if getattr(self, "_iso", False) else state).items():'),
      (BD, '                self._move(trainer, iso_child, iso_parent)', '                self._iso = True\n                self._move(trainer, iso_child, iso_parent)\n                self._iso = False')),
    m('M46', 'BOOK', 'A2 latent history not copied on iso moves',
      (BD, 'if history is not None:', 'if history is not None and not getattr(self, "_iso", False):'),
      (BD, '                self._move(trainer, iso_child, iso_parent)', '                self._iso = True\n                self._move(trainer, iso_child, iso_parent)\n                self._iso = False')),
    m('M47', 'BOOK', 'isolation also applied in a dry run',
      (BD, '        if self.dry_run:\n            return last\n', '        if self.dry_run and not self.isolation:\n            return last\n')),
    m('M48', 'BOOK', 'iso move counter not incremented (iso_moves stays 0)',
      (BD, 'c["iso_moves"] += len(dead)\n', 'pass\n')),
    m('M49', 'BOOK', 'load_state_dict does not restore the counters (iso counters reset after a resume)',
      (BD, 'self.counters, self.last = dict(state["counters"]), dict(state["last"])', 'self.last = dict(state["last"])')),
    # ------------------------------------------------------------------ RNG
    m('M50', 'RNG', 'one random number drawn from the private stream in EVERY evaluation, flag off included',
      (BD, '            u = torch.rand(self.N, device=z.device, dtype=torch.float64, generator=self.stream)\n',
           '            u = torch.rand(self.N, device=z.device, dtype=torch.float64, generator=self.stream)\n            torch.rand(1, device=z.device, generator=self.stream)\n')),
    m('M51', 'RNG', 'flag on: parent draw made before the guard (stream advances even when nothing is flagged)',
      (BD, '        empty = child[:0]\n        if not acted:', '        empty = child[:0]\n        torch.rand(1, device=trainer.prior.z.device, generator=self.stream)\n        if not acted:')),
    m('M52', 'RNG', 'parent draws taken from the global RNG instead of the private stream',
      (BD, 'draw = torch.rand(dist.shape, device=dist.device, generator=self.stream)', 'draw = torch.rand(dist.shape, device=dist.device)')),
    # ------------------------------------------------------------------ recipe validation
    m('M53', 'VALID', 'recipe accepts isolation with data-space birth-death',
      (RC, "if self.birth_death_isolation and not (self.particle_birth_death and self.birth_death_space == \"critic\"):",
           "if False:")),
    m('M54', 'VALID', 'recipe does not require a boolean',
      (RC, "if type(self.birth_death_isolation) is not bool:", "if False:")),
]
