"""Render the compact measured readout from certified results only."""
from pathlib import Path
from collections import Counter
from experiments.forge.contracts import read_json
OUT=Path(__file__).resolve().parent
ROLES=('winner','direction','transport','both')
TASKS=('gaussian1d_smoke','gaussian1d_stability','trajectory_transport_round5_v1','residual_student_transport_round5_v1','mid_scale_identity_transport_round5_v1','vector_unequal_mass','vector_two_broad')
LABELS=('Gaussian smoke','Own Gaussian retention','Trajectory variant','Residual variant','Mid-scale variant','Unequal mass','Two broad')

def main():
    result=read_json(OUT/'results.json');rows={(r['role'],r['task_id']):r for r in result['task_results']}
    union=all(rows['both',t]['gate_status']=='PASS' for t in TASKS[2:])
    global_repair=union and rows['both','gaussian1d_stability']['gate_status']=='PASS'
    prereg=read_json(OUT/'preregistration.json')
    budgets={t:read_json(OUT.parents[4]/f'configs/forge/tasks/{t}.json')['execution']['steps'] for t in TASKS}
    committed=sum(budgets[t]-(1000 if t=='gaussian1d_stability' else 0) for role,t in rows if rows[role,t]['gate_status'] in ('PASS','FAIL'))
    text=['# Conditional integration, round five','',
        ('**Direction blend plus local-v2 retains the conditional and rare/broad density repairs in one global recipe.**' if union else '**Direction blend plus local-v2 does not retain the complete conditional and rare/broad repair union.**'),
        ('Gaussian retention also passes in this declared subset.' if global_repair else 'Gaussian full retention remains a separate required limitation; the result does not establish a global replacement.'),
        'This completed four-arm bounded diagnostic adds explicit public consumers to the previously unsupported conditional hosts. It grants no ordinary qualification, accepted calibration or default promotion. [PR373](https://github.com/255BITS/ParticleGAN/pull/373) remains ready and unmerged.','',
        '| Original gate / explicit variant | Winner | Direction only | Local-v2 | Both |','| --- | --- | --- | --- | --- |']
    for task,label in zip(TASKS,LABELS):text.append('| '+label+' | '+' | '.join(rows[r,task]['gate_status'] for r in ROLES)+' |')
    text+=['| Declared subset | '+' | '.join(', '.join(f'{n} {k}' for k,n in Counter(rows[r,t]['gate_status'] for t in TASKS).items()) for r in ROLES)+' |','',
        '[Final metrics and sustained graders](results.json), [compact certificates](receipts.json), [protocol proofs](provenance.json), [byte-exact singleton and activation audit](audit.json), [freeze](freeze.json), [scorer controls](scorer-controls.json) and [preregistration](preregistration.json) bind these cells. This is a scoped comparison, not a new full-suite leaderboard. The parent owns the single current inventory; the original winner retains its archived 7/21 Tier2 contract.','',
        '| Endpoint diagnostic | Winner | Direction only | Local-v2 | Both |','| --- | ---: | ---: | ---: | ---: |']
    for task,metric,label in [('trajectory_transport_round5_v1','identity_mse','Trajectory MSE'),('residual_student_transport_round5_v1','identity_mse','Residual MSE'),('residual_student_transport_round5_v1','success_rate','Residual own-pad success'),('residual_student_transport_round5_v1','wrong_pad_rate','Residual wrong-pad rate'),('mid_scale_identity_transport_round5_v1','identity_at_mid','Mid-scale identity'),('vector_unequal_mass','component_covariance_error','Rare-mixture full covariance'),('vector_unequal_mass','mass_tv','Rare-mixture mass TV'),('vector_two_broad','component_covariance_error','Broad full covariance'),('gaussian1d_stability','cdf_ks','Gaussian final KS')]:
        text.append('| '+label+' | '+' | '.join(f'{rows[r,task]["metrics"][metric]:.9g}' if metric in rows[r,task]['metrics'] else 'BLOCKED' for r in ROLES)+' |')
    text+=['','Endpoint values are descriptive. Trajectory requires identity MSE <=.02; residual additionally requires every correct landing and zero wrong-pad rate. Mid-scale retains all eight concept/identity bounds. Each conditional and vector task requires five terminal full passing checks. Unequal mass retains its original full covariance/eigenvalue, rare-mass, quality, transport and TV gates; computed core/spill metrics remain diagnostics. A favorable scalar never replaces these gates.','',
        '| Arm | Gaussian stationary | Shift hold | Deadline reacquisition |','| --- | --- | --- | --- |']
    for role in ROLES:
        g=rows[role,'gaussian1d_stability']['evaluator_summary'] if 'evaluator_summary' in rows[role,'gaussian1d_stability'] else {}
        text.append(f'| {role} | {g.get("stationary_passes","?")}/{g.get("stationary_checks",72)} | {g.get("shift_hold_passes","?")}/{g.get("shift_hold_checks",24)} | {g.get("reacquisition_status","BLOCKED")} |')
    text+=['','Smoke requires an independently confirmed scheduled passing state and still completes 1,000 updates. It does not certify the endpoint. Retention restores each arm\'s own complete smoke state and original horizon/streams, adds the unchanged 5,000 updates, and requires all 72 stationary checks, deadline reacquisition and all 24 shifted hold checks. Frozen Gaussian/vector adapters retain their actual same-real-tensor D/G law. Clean/live evidence does not borrow noisy or EMA scores.','',
        'The matched comparison resolves the interface question: local-v2 alone fails both identities, whereas adding the unchanged direction blend restores their full gates. This establishes the measured union for the explicit output-marginal variants; it does not attribute a unique historical conflict cause or prove conditional generalization beyond the frozen panels.','',
        'Against local-v2, BOTH improves rare full covariance .522577 to .386670 and extends the passing suffix 5 to 9, while broad covariance worsens .226564 to .331816 within its PASS gate. Conditional passing suffixes are trajectory 18, residual 20 and mid-scale 21 versus direction-only 19/21/20. Lower endpoint identity MSE does not establish faster or statistically superior training. Gaussian stationary passes regress 28/72 to 6/72 and shifted hold 11/24 to 2/24 despite final KS improving .060653 to .033669. Temporal retention therefore remains the tradeoff.','',
        '## Exact mechanism and explicit consumers','',
        'All arms retain the exact winning nonsaturating BCAP recipe: full DualNorm, momentum 0, smoothing .001, per-offset layout, G/E .012, D .018, prior .030, constant floors 1, BCAP coefficient 1/cap 1/every update, no additive training noise, EMA or extra scalar prior regularization. The deltas are only `constraint_geometry_mode` (none or exact PR367 `direction_blend`) and the two exact local-v2 weights (0 or1), with 32 deterministic directions. Strict-progress and local-v2 module bytes remain unchanged. Direction uses the same full common-descent blend as PR367, without finite probes; transport is added to the total objective and is never a new protected loss.','',
        'The new public `OutputMarginalTransport` consumer adds the existing empirical sliced-W2 and relative local real-anchor feature losses. Real targets, anchors, fourth-neighbor widths and normalizers are detached. Gradients flow from generated outputs to the original network and learned prior locations. Conditioning is checked but excluded from the transport distance; no oracle evaluator geometry, labels, new draw, task-specific weight or serving change enters. Zero weights return the original loss tensor.','',
        '| Explicit source-bound variant | Sample-space and training target law | Existing protected signals |','| --- | --- | --- |',
        '| trajectory_transport_round5_v1 |12 generated fast arcs [12,16] versus existing full fast target panel; original slow arcs condition G/D and are excluded from transport distance | Original adversarial only; **no new trajectory paired-MSE supervision** |',
        '| residual_student_transport_round5_v1 | Same 12 fast/target arcs, original slow conditioning; original both-land mask retained | Original adversarial plus original active paired residual |',
        '| mid_scale_identity_transport_round5_v1 | One generated/teacher state per original training scale (-1, 0, .5, 1), [4,4]; no replicated identical rows in the transport panel; scale labels excluded from distance | Original adversarial plus original paired cover |','',
        'These are output-marginal losses: a row-permuted target admits zero transport loss while failing identity. [Saved endpoint probes](prior-evidence.json) and destructive controls retain that distinction. Marginal set matching cannot silently replace temporal or conditional correctness. The consumers reuse existing G-phase tensors; they do not add real target draws or generator forwards. Mid-scale retains its original explicit zero-origin parameter fixture and public KEEP initializer policy, with no sampled prior; it is a separate host cohort from the learned conditional networks. Trajectory/residual enumerate learned cloud locations under their original explicit exceptions. Scalar/vector hosts retain positive-width learned MoG with fixed widths and uniform weights.','',
        'All four arms use the same variants. Architecture, data/targets, actual seen batches, priors, initializer, sampling, committed-update budget, original evaluation cadence and full thresholds remain fixed. Each variant retains its original question ID. The three original cards remain unchanged and transport-bearing original contracts remain BLOCKED. Two-pole is excluded and has no implicit consumer. Native, unequal width, images and words are unmeasured.','',
        'The exact direction and local-v2 implementations come from independently archived PR367/368 evidence, inspected before registration. [Gretton et al.](https://www.jmlr.org/papers/v13/gretton12a.html) provide MMD theory and [Li et al.](https://proceedings.mlr.press/v37/li15.html) show differentiable generator moment matching; this finite data-dependent feature loss has no characteristic-population guarantee. [Sener and Koltun](https://arxiv.org/abs/1810.04650) provide multiobjective context. The analogies and frozen-batch first-order property do not prove stochastic GAN density, finite descent or retention convergence.','',
        '## Activation and source-bound checks','',
        '| Both-arm conditional host | Active transport calls | Direction conflicts | Pareto stalls |','| --- | ---: | ---: | ---: |']
    for task in TASKS[2:5]:
        row=rows['both',task];consumer=row.get('component_transport') or {};stats=(row.get('direction_blend') or [{}])[0]
        text.append(f'| {task} | {consumer.get("active_calls",0)} | {stats.get("conflict_steps",0)} | {stats.get("pareto_stalls",0)} |')
    text+=['','The audit verifies actual consumer invocation on every conditional update, inactive bitwise behavior, exact archived singleton numerical states/observations/outputs and matching public initial hashes and every consumed named stream across arms. Constructor, data, training noise, prior sampling and evaluation states are checkpointed. Equal target panels and vector batch-sequence digests provide actual-input proofs; source/runtime equality alone is insufficient. All exercised scientific bytes and archived task/qualification/telemetry files remain unchanged after training. Saved endpoint inspection and audits add no training or training-stream draws.','',
        '## Accounting, reproduction and recommendation','',
        f'Measured source **{result["source_commit"]}**, digest `{result["source_digest"]}`. {result["scientific_attempts"]} paid attempts, {result["scientific_retries"]} retries; paid main-worker wall time **{result["paid_seconds"]:.6f} seconds**. Initial full reservations 38,880 seconds, executed allowances {result["executed_full_reservations"]:g}, campaign ceiling 42,000; ancillary allowance 1,200 within track ceiling 43,200. The 28 declared cells add {committed:,} certified new committed host updates; restored smoke prefixes are counted once. Contended timings establish cost, not speed superiority. Bulk stdout, JSONL, checkpoints and tensors remain on the artifact drive. Scoring-only oracle target draws are a separate witness cohort, not seed experiments or training streams.','',
        ('Retain BOTH as a **scoped measured union** of the conditional and rare/broad repairs under this exact consumer law, while preserving its Gaussian retention limitation.' if union else 'Reject this exact BOTH package as a complete conditional/density union; preserve the independent direction and local-v2 repairs under their original contracts.'),
        'Stop this finite campaign. No additional candidate, tuning, seed study, unchanged continuation, merge or promotion follows. Any transfer or revised consumer requires a separately authorized bounded question.','',
        '[Actual-training GIF index](media/index.json) links all measured states; GIFs illustrate numerical goals without replacing graders. [Public execution](run.py), [preparation](prepare.py), [publication](publish.py), [audit](audit.py), [scorer controls](scorer_controls.py) and [readout generation](summarize.py) retain reproduction sources. Runs require the pinned trained source and the original artifacts; missing archives block saved-state verification rather than authorizing reruns.','',
        '```sh','PYTHONPATH=. /home/martyn/dev/ParticleGAN/.venv/bin/python reports/forge/bcap-physics/conditional_integration/round5/publish.py',
        'PYTHONPATH=. /home/martyn/dev/ParticleGAN/.venv/bin/python reports/forge/bcap-physics/conditional_integration/round5/audit.py',
        'tail -F /mnt/ml7tb/ParticleGAN-forge/bcap-physics-round5-20261009/conditional_integration/logs/driver.log','```','']
    text += ['## Actual-training media', '', '| Task | Winner | Direction only | Local-v2 | Both |', '| --- | --- | --- | --- | --- |']
    for task,label in zip(TASKS,LABELS):
        text.append('| '+label+' | '+' | '.join(f'[GIF](media/{role}-{task}.gif)' for role in ROLES)+' |')
    text.append('')
    (OUT/'README.md').write_text('\n'.join(text))
    print('Published measured text; retained union:',union,'global repair:',global_repair)
if __name__=='__main__':main()
