"""Write the measured scoped readout; never launch, sample or regrade training."""
from pathlib import Path
from experiments.forge.contracts import read_json
OUT=Path(__file__).resolve().parent
ROLES=('local','direction','finite');TASKS=('gaussian1d_smoke','gaussian1d_stability','vector_unequal_mass','vector_two_broad','vector_unequal_width')
def main():
    results=read_json(OUT/'results.json');audit=read_json(OUT/'audit.json');diag=read_json(OUT/'temporal-diagnostics.json')
    rows={(r['role'],r['task_id']):r for r in results['task_results']};details={(r['role'],r['task_id']):r for r in diag['rows']}
    def cell(role,tid):
        r=rows[(role,tid)];d=details[(role,tid)];m=r['metrics'];e=d['evaluator_result']
        if tid=='gaussian1d_smoke':return f"**{r['gate_status']}**, first confirmation {e['first_confirmed_step']}; KS {m['cdf_ks']:.6f}"
        if tid=='gaussian1d_stability':return f"**{r['gate_status']}**, stationary {e['stationary_passes']}/72, deadline {e['reacquisition_status']}, hold {e['shift_hold_passes']}/24; KS {m['cdf_ks']:.6f}"
        return f"**{r['gate_status']}**, full covariance {m['component_covariance_error']:.6f}; suffix {d['terminal_passing_suffix']}"
    lines=['# Gaussian regression: finite acceptance versus direction','',
        '**Removing finite acceptance preserves the rare/broad repair but does not restore Gaussian retention.** Direction plus local-v2 finishes 3 PASS / 2 FAIL, as do local-v2 and strict finite plus local-v2. Direction reaches endpoint KS .033669 within the .05 bound, while only 6/72 stationary checks and 2/24 shifted-hold checks pass and deadline reacquisition fails. Its unequal-width covariance regresses. No global repair or ordinary qualification follows.','',
        'This completed three-arm bounded diagnostic is [PR374](https://github.com/255BITS/ParticleGAN/pull/374), stacked on [PR368](https://github.com/255BITS/ParticleGAN/pull/368), ready and unmerged. Each arm uses one global trainer configuration, protocol seed 0, original tasks and complete gates. Parent owns the single current technique leaderboard; this is a scoped comparison table.','',
        '| Original task | Exact local-v2 | PR367 direction + local-v2 | PR368 strict finite + local-v2 |','| --- | --- | --- | --- |']
    for tid in TASKS:lines.append('| '+tid+' | '+' | '.join(cell(role,tid) for role in ROLES)+' |')
    lines+=['',
        'The registered endpoint KS forecast is observed for direction. The complete continuous-learning hypothesis fails: all 72 stationary checks, the deadline\'s last five reacquisition checks, and all 24 shifted-hold checks are required. A terminal pass or attractive endpoint cannot replace that rule. Smoke independently confirms an earlier scheduled state while completing 1,000 updates; stability restores each arm\'s own completed 1,000-update checkpoint, without resetting optimizer history or streams. First confirmation 167 / 375 / 459 therefore describes acquisition timing, not the checkpoint step restored or retention.','',
        '## Density repair and guardrails','',
        '| Unequal-mass endpoint | Local-v2 | Direction | Finite |','| --- | --- | --- | --- |']
    for metric in ('component_covariance_error','component_min_eigen_ratio','mass_tv','hq','min_mass_ratio','max_component_spill'):
        lines.append('| '+metric+' | '+' | '.join(f"{rows[(role,'vector_unequal_mass')]['metrics'][metric]:.6f}" for role in ROLES)+' |')
    lines+=['',
        'All three retain the rare task\'s complete five-terminal-check gate and broad-mixture PASS. Direction extends the rare passing suffix from 5 to 9 and reduces covariance, but slightly worsens mass TV and HQ; finite retains covariance .350241 and suffix 9. These are descriptive deterministic comparisons, not statistical superiority or a pooled family winner.','',
        'Unequal width remains FAIL in every arm. Direction worsens uncensored full covariance 2.480438 → 3.590511, against the unchanged .85 bound. [Temporal diagnostics](temporal-diagnostics.json) retain every endpoint failure, covariance per component, core covariance, spill, mass and actual sample counts. All four components remain represented; lower averaged or core covariance cannot replace the full served-law gate. Gaussian draws remain finite, and failure includes CDF shape and temporal instability rather than an exception or borrowed checkpoint.','',
        '## What the finite layer changes','',
        '| Task | Direction conflicts / steps | Finite conflicts / steps | Finite backtracking reductions / rejections |','| --- | --- | --- | --- |']
    for tid in TASKS:
        a=rows[('direction',tid)]['strict_progress'][0];b=rows[('finite',tid)]['strict_progress'][0]
        n=6000 if tid=='gaussian1d_stability' else 1000 if tid=='gaussian1d_smoke' else 1200
        lines.append(f"| {tid} | {a['conflict_steps']}/{n} | {b['conflict_steps']}/{n} | {b['backtracks']} / {b['rejected_steps']} |")
    lines+=['',
        'Stability counters include the 1,000-update smoke prefix. Direction always applies the unchanged common-descent blend at full scale and never calls a finite evaluator. Strict finite backtracks on conflicting proposals to certify same-batch protected adversarial decrease. All 1,407 Gaussian conflicts are accepted with zero rejection, 151 reductions, and minimum scale .25. Direction takes a different path after scaling is removed; lower endpoint KS does not identify a unique historical cause. Endpoint aggregate activity plus scheduled quality curves cannot assign every later quality failure to a particular conflict event.','',
        'The exact blend mixes the nonascent projection and negative normalized protected gradient. Its local directional interpretation is related to [Sener and Koltun](https://arxiv.org/abs/1810.04650); finite sufficient decrease follows an [Armijo-style construction](https://msp.org/pjm/1966/16-1/pjm-v16-n1-p01-s.pdf). Their deterministic properties do not establish distribution convergence in this moving stochastic game. No transport term becomes another protected loss and no target labels or oracle geometry enter training.','',
        '## Source, protocol and execution','',
        f"All arms execute commit `{results['source_commit']}`, digest `{results['source_digest']}`. [Audit](audit.json) verifies {audit['source_snapshot_files_verified']} frozen files, {audit['current_scientific_files_verified']} current scientific files, all 15 final certificate sets and actual-training GIFs, and {len(audit['archived_control_parity'])} bitwise archived-control comparisons. Local-v2 and finite reproduce round-four smoke/stability/rare/broad observations, samples, model/optimizer tensors and consumed streams; archived results are context, not reused qualification. Width is also reproduced as a matched new-source control in all arms.", '',
        'The [four-state saved restoration](prior-evidence.json) preceded preregistration and adds zero updates or sampling. The direction module is byte-exact PR367; strict and local-v2 modules are byte-exact PR368. All 67 original task and qualification/telemetry snapshots remain unchanged. Each task\'s actual initial model hashes, consumed context and trainer streams, and batch digests match across all three arms. Vector batches are reconstructed with disposable RNGs from the recorded initial seed and checked against the exact final data-stream state; the frozen adapter did not log their digest. Read-only replay adds no training or served-model draws. Archived array parity excludes only opaque training-state hashes containing unused ambient CPU/CUDA states; actual outputs, metrics, model/optimizer tensors and every consumed named stream are compared. Constructor, data, prior/noise and evaluation streams are isolated and checkpointed. The frozen Gaussian/vector adapters retain their actual same-real-tensor D/G reuse.','',
        'The exact saved BCAP winner is nonsaturating, full DualNorm smoothing .001/momentum0/per_offset, G .012, D .018, prior .030, constant floors1, cap/coefficient1 every update, zero additive training noise and clean/live scoring. Bare `get_recipe("bcap")` is historical Adam. Local-v2 has global/local weights 1 and 32 projections. Only geometry mode differs: none, direction_blend, strict_progress. Gaussian uses learned uniform 256-MoG sigma .1; vector priors retain sigma .025, fixed uniform weights and learnable locations. Architecture, target law, initializer, actual batches, sampling, update budget and evaluation cadence are fixed within each task.','',
        f"All 15 final jobs complete: 9 PASS / 6 FAIL, no final BLOCKED, INCOMPLETE or INVALID. There are 16 paid attempts including one retained strict-smoke timeout. Main paid worker wall time is **{results['paid_seconds']:.6f} seconds**; initial full reservations 18,360 plus retry 120 total **18,480**. Queue ceiling 21,180 plus saved restoration 120 and bounded software/scorer 300 allowances equals the 21,600 track cap. Certified complete arms account for 28,800 updates; the discarded timeout has an uncertified partial prefix, its last logged observation 42. Its 121.149060-second INCOMPLETE receipt remains unchanged in [execution history](execution-history.json).", '',
        'Transient host RAM contention then blocked pending work without paid launches. The unchanged-source recovery uses physical GPU 1/logical cuda:0, five-second queue polling and pre-import BLAS/OpenMP threads 1; scientific Torch thread budget 1 remains unchanged. Bitwise archived parity and complete stream checks verify that this execution recovery changed no compared training trajectory. Contention and startup time are accounting, not optimizer-speed claims. All subscriptions are concluded, reservations zero, and workers/watchers stopped. Bulk stdout, JSONL, JUnit, checkpoints and tensors remain on the artifact drive.','',
        'The focused software/protocol suite passes 58 checks, covering CPU/CUDA float32/64, public recipe construction, checkpoint resume, inactive parity, nonlinear overshoot without evaluator calls, unchanged critic/streams and adversarial-only protection with both transport terms. [Oracle/destructive controls](scorer-controls.json) validate full Gaussian and vector scorers. Publication recomputes 648 saved primary metric sets and adds no updates or sampling. Forge validates; summaries-only compilation/check preserves published qualification/telemetry. Later files are report/audit helpers, not another measured trainer revision.','',
        '## Actual-training media and decision','',
        '| Task | Local-v2 | Direction | Finite |','| --- | --- | --- | --- |']
    for tid in TASKS:lines.append('| '+tid+' | '+' | '.join(f'[GIF](media/{role}-{tid}.gif)' for role in ROLES)+' |')
    lines+=['',
        '**Retain local-v2 as the reference; do not adopt either composition as a global replacement.** Direction retains the scoped rare/broad repair and removes finite evaluator work, but it fails retention and worsens the width guardrail. Finite retains its same-batch certificate and slightly better rare covariance, with the original Gaussian regression. Neither finite removal, batch descent, acquisition nor endpoint KS alone resolves continuous learning. Stop this comparison without a sweep, new seed, continuation, merge or promotion. Any further question should inspect the saved Gaussian trajectory and competing adversarial/empirical transport fields rather than tune finite acceptance from this endpoint.','',
        '[Final metrics](results.json), [compact receipts](receipts.json), [matched provenance](provenance.json), [concluded studies](readouts.json) and [media identities](media/index.json) preserve exact evidence. Read-only reproduction:', '',
        '```sh','PYTHONPATH=. /home/martyn/dev/ParticleGAN/.venv/bin/python reports/forge/bcap-physics/gaussian_regression/round5/publish.py','PYTHONPATH=. /home/martyn/dev/ParticleGAN/.venv/bin/python reports/forge/bcap-physics/gaussian_regression/round5/audit.py','tail -F /mnt/ml7tb/ParticleGAN-forge/bcap-physics-round5-20261009/gaussian_regression/queue/events.jsonl','tail -F /mnt/ml7tb/ParticleGAN-forge/bcap-physics-round5-20261009/gaussian_regression/logs/driver.log','```','']
    (OUT/'README.md').write_text('\n'.join(lines))
if __name__=='__main__':main()
