"""Independent frozen image source/configuration binding, no model execution."""
from pathlib import Path
import ast,hashlib,json,zipfile
E=Path(__file__).resolve().parents[1];B=E/'port-source/new-init-image-screen';R=E/'image-screen-review';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();h=lambda b:hashlib.sha256(b).hexdigest();read=lambda p:json.loads(p.read_text());p=read(B/'host-source-proof.json');seal=read(B/'bundle-sha256.json');assert {f.name:sha(f) for f in B.iterdir() if f.is_file() and f.name!='bundle-sha256.json'}==seal
assert sha(Path(p['source_zip']))==p['source_zip_sha256'];frozen=(B/'frozen_image_host.py').read_text();defs={n.name:ast.get_source_segment(frozen,n) for n in ast.parse(frozen).body if isinstance(n,(ast.FunctionDef,ast.ClassDef))}
with zipfile.ZipFile(p['source_zip']) as z:
 for item in p['definitions']:
  s=z.read(item['source']);assert h(s)==item['source_file_sha256'];s=s.decode();node=next(n for n in ast.parse(s).body if isinstance(n,(ast.FunctionDef,ast.ClassDef)) and n.name==item['definition']);assert ast.get_source_segment(s,node)==defs[node.name]
 plan=json.loads(z.read('benchmarks/transfer_suite/plans/default_comparison.json'));specs=read(B/'task-specs.json')
 for name,spec in specs.items():
  original=next(x['spec'] for x in plan if x['spec']['name']==name);assert spec==original
  assert (spec['architecture'],spec['width'],spec['z_dim'],spec['particles'],spec['batch_size'],spec['steps'])==('residual_upsample',16,8,32,32,600)
  assert spec['thresholds']['minimum_stable_checks']==5 and spec['thresholds']['observations']==24
receipt=read(R/'dv12-intensity2-cpu/cpu-preflight.json');assert receipt['status']=='PASS_CPU_ZERO_STEP' and not receipt['cuda_initialized'];assert receipt['initializer_rng_neutral'] and receipt['repeated_without_rng_reset'];assert receipt['initial_material']['completed_steps']==0
for name,digest in receipt['source_sha256'].items():
 if (B/name).is_file():assert sha(B/name)==digest
out={'status':'PASS_SOURCE_AND_DV12_IMAGE_INITIALIZATION','bundle_sha256':sha(B/'bundle-sha256.json'),'cpu_receipt':str(R/'dv12-intensity2-cpu/cpu-preflight.json'),'cpu_receipt_sha256':sha(R/'dv12-intensity2-cpu/cpu-preflight.json'),'candidate':'API-DV12-new-init','cpu_task':'img_intensity2','six_frozen_definitions_exact':True,'four_frozen_specs_exact':True,'model_resources':dict(architecture='residual_upsample',width=16,z_dim=8,particles=32,batch=32,steps=600),'initializer':dict(repeated_all_non_rng_state=True,R2_normal_std=1.,rng_neutral=True,zero_learner_steps=True,CUDA_initialized=False),'source_transaction':'CPU G→D→prior then CUDA; shared globalCUDA data+latent, independent package noise generator; same real batch in both losses, complete serial publicstep, all600 dry/actual source and accepted cursors','scoring':'All32 prior rows; unchanged generation with private2303+completed stream; live/EMA24 checks25..600, same original HQ/mode thresholds and final5','limits':['Only DV12 intensity2 has a fresh CPU constructor proof; other candidate/task invocations need their declared matching receipt.','All4 cards share model construction but task source/thresholds remain separately pinned.','No training or GPU, no quality inheritance, no blanket broader qualification.','Own runtime must satisfy actualCUDA model/CPU material assertion, device-local bandwidth and600 draw receipts.']}
(R/'source-audit.json').write_text(json.dumps(out,indent=2)+'\n');(R/'source-audit.md').write_text('''# Fixed-initialization image harness review\n\nSource and DV12 intensity2 CPU initialization PASS, bound to bundlef334d0038872de81dc2ac44d9b9a884c11bc66f9811945dd17f289f77d0b1ed5. All six complete model/template/scorer definitions and all four task specifications match the immutable archived image host. Models are residual-upsample width16/z8 with32 particles/batch32 and600 updates. Original templates,24 checks every25, HQ/mode bounds and final-five rule are unchanged.\n\nThe source retains CPU G→D→prior construction, actual public initializers, then CUDA transfer. The public trainer derives bandwidth/EMA/optimizer state afterward. Shared globalCUDA data/latent stream remains seed0, checked unchanged after constructors. A private clone computes all600 data/index/cursor receipts before updates; actual full serial publicsteps must match them. The same real batch feeds both losses. Evaluation enumerates all32 prior rows and uses the unchanged candidate generation path with isolated noise2303+completed, restoring training/caller state.\n\nOne independent guarded CPU check used the unchanged DV12 package on intensity2. It compared complete non-RNG state across two constructors with intervening random draws, verified exact R2 normalstd1 prior and initializer RNG neutrality, and checked device-local derived geometry/native empty state. Forward/backward/optimizer execution was forbidden and CUDA remained uninitialized. The runtime must also assert exact initialized CUDA model/buffer bytes against this CPU proof.\n\nThis is preparation only and clears only the declared DV12 intensity2 constructor proof. Other candidate/task executions still require matching receipts; no old image quality is inherited. Source/proof hashes and boundaries are in source-audit.json.\n''');print(json.dumps({k:out[k] for k in ['status','bundle_sha256','cpu_receipt','cpu_receipt_sha256']}))
