"""Independent original inline-probe source and constructor binding; no Torch."""
from pathlib import Path
import ast,hashlib,json,zipfile
Q=Path(__file__).resolve().parent;E=Q.parents[1];K=E/'research-mode-hold-preparation';read=lambda p:json.loads(p.read_text());sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();rows=read(Q/'prepared-index.json')['rows'];kplan=read(K/'source-plan.json');base=(K/'run_research_mode_hold.py').read_text();out=[]
expected={'5cc4d7b1a5e68b8387233d83d3a4bab83c018e69ea6623e41032b690eb6bbeef':('penalty','_phi'),'6008a4b0baa69ab21500d6f71bc3b3cfd852860f186f85a7b1123d6db4b8ed3b':('penalty','smooth_cap_phi'),'459b03b1b062ae5debb391512f2bde0bfbcd521950caaedadead18ab98108d9f':('r1_only_penalty','_phi'),'b68488e3901c78c63c8275b335c75ecc0c59a69c93380417023d416baab25419':('hybrid_penalty','_phi'),'e35c75d0d40175450e1f23f530a9086010a97195741d90f7096be7227d97b8f8':('asymmetric_cap','_phi')}
for row in rows:
 B=Path(row['directory']);plan=read(B/'source-plan.json');manifest=read(B/'manifest.json');proofpath=Path(row['required_review']);proof=read(proofpath)
 assert sha(B/'manifest.json')==row['manifest_sha256']==proof['manifest_sha256']
 assert sha(B/'source-plan.json')==row['source_plan_sha256']==proof['source_plan_sha256']
 assert sha(B/'initialization_bridge.py')==sha(K/'initialization_bridge.py')==proof['bridge_sha256']
 for name,want in manifest['files'].items():assert sha(B/name)==want
 s=(B/'run_research_mode_hold.py').read_text().replace('exact original-inline-penalty research screen','exact research-KA2 screen').replace("HERE/'candidate-source'","HERE/'ka2-source'").replace("candidate=plan['candidate']","candidate='RESEARCH-KA2-new-init'").replace("optimizer_state=plan['optimizer_state']", "optimizer_state='Original research probe eager CUDA scalar counters; not native public lazy Adam'")
 assert s==base
 assert plan['historical_runtime_files']==kplan['historical_runtime_files'] and plan['initializer_package']==kplan['initializer_package']
 assert plan['probe_contract']['kind']=='ORIGINAL_INLINE_PENALTY_PROBE'
 original=Path(plan['source_candidate'])
 for name,want in plan['candidate_files'].items():assert sha(B/'candidate-source'/name)==want==sha(original/name)
 snapshot=plan['source_definition']['source_binding']['availability_snapshot'];assert snapshot and sha(Path(snapshot['path']))==snapshot['sha256']
 with zipfile.ZipFile(snapshot['path']) as z:
  for name in plan['source_definition']['active_local_sources']:
   options=[n for n in z.namelist() if n==name or n.endswith('/'+name)];assert len(options)==1;assert hashlib.sha256(z.read(options[0])).hexdigest()==plan['candidate_files'][name]
 probe_sha=plan['candidate_files']['probe.py'];assert proof['original_probe_sha256']==probe_sha
 assert (proof['penalty_binding']['penalty'],proof['penalty_binding']['phi'])==expected[probe_sha]
 assert proof['status']=='PASS' and all(proof['checks'].values()) and not proof['cuda_initialized'] and proof['learner_steps']==0
 assert 'no response registration' in proof['prior_binding_contract']
 assert not any(n in plan['candidate_files'] for n in ('mechanism.py','latent.py','response.py','checkpoint.py'))
 item={'status':'PASS_ORIGINAL_PROBE_SOURCE_AND_CPU_INITIALIZATION','candidate':row['candidate'],'manifest_sha256':row['manifest_sha256'],'source_plan_sha256':row['source_plan_sha256'],'cpu_proof_sha256':sha(proofpath),'probe_sha256':probe_sha,'penalty_binding':proof['penalty_binding'],'ordinary_Adam_preserved':True,'added_later_hooks':False,'constructor_checks':proof['checks'],'limits':['Original probe/config run, not shared85 six-hook pipeline or publicGANTrainer','No forward/backward/optimizer construction or step; CPUcapture occurs immediately after model initialization','No original finalcheckpoint retained; no continuation/replay claim','Fresh quality required; historical horizon policies and eligibility remain unchanged']}
 (proofpath.parent/'source-review.json').write_text(json.dumps(item,indent=2)+'\n');(proofpath.parent/'source-review.md').write_text('# '+row['candidate']+' original-probe initialization review\n\nPASS. Exact original probe/config and all declared local files match retained source and inventory snapshot. The ordinary Adam wrapper is preserved; no later mechanism/latent/response/eager-state stack is injected. The CPU reviewer runs the actual original probe setup, including its inline penalty assignment, then stops at the initializer capture before optimizer construction or any forward. All seven constructor invariants pass; the plain historical prior class remains unchanged, with no invented registration hook. Active penalty function identities match this exact probe variant.\n\nThe same reviewed bridge and complete historical runtime are retained. The external runner differs from the reviewed template only in source directory, report label, descriptive optimizer metadata and docstring. Initial CUDA model tensors must match the CPU proof before updates. This clears preparation only: no quality is inherited, original schedules remain, and the old probe has no final checkpoint supporting continuation/replay.\n')
 out.append(item)
assert len(out)==11
summary={'status':'PASS_INITIALIZATION_ONLY','candidates':11,'index_sha256':sha(Q/'prepared-index.json'),'rows':out,'CPU_max_concurrency':3,'training_steps':0,'scope':'Separate exact original inline-penalty/config probes; no later hook injection'}
(Q/'independent-all11-review.json').write_text(json.dumps(summary,indent=2)+'\n');(Q/'independent-all11-review.md').write_text('''# Eleven early probes: independent preparation review\n\nAll11 exact original probe/config preparations pass source and fresh CPU initialization review. Five distinct probe source hashes cover unchanged/config-only, smooth radial cap, R1-only, hybrid fake-cap and asymmetric-cap variants. Each original probe executes its own setup under CPU capture; no later mechanism, response, latent or checkpoint module is injected. Ordinary Adam remains original.\n\nThe checker stops after initialized G/D/prior capture and forbids forwards, backward, optimizer construction and optimizer steps. Every variant passes repeated construction without RNG reset, RNG-neutral public initialization, original constructor cursor, all parameter/buffer equality, plain original prior class preservation, exception restoration and explicit unsupported-head rejection. CUDA stays uninitialized. The prior-registration proof field explicitly means preservation of the plain original class here, not fabricated response IDs.\n\nEach row binds original source/snapshot, prepared seal, unchanged bridge, declared common historical runtime, CPU proof and active inline penalty function. No old quality is inherited. The original probe variants do not retain final checkpoints, so no continuation/replay evidence is claimed. See independent-all11-review.json and per-row source-review/cpu-constructor-proof files.\n''');print(json.dumps({'status':summary['status'],'candidates':11,'source_hash_groups':len(expected),'summary_sha256':sha(Q/'independent-all11-review.json')}))
