import gzip,hashlib,json
from pathlib import Path
out=Path('/tmp/pr36-solvability-mog-afe6152')
rows=json.loads((out/'summary.json').read_text())
assert len(rows)==16
lines=['# Original-budget MoG training controls','','Exactly16 actual GAN episodes, fixed seed0 and cosine schedule, original256 particles/1200 updates/architecture, unchanged task thresholds. Eight shared settings cross unequal-mass and unequal-width targets. This is separate from the target/representation-oracle audit. No final full PASS or sustained full PASS was found. All16 episodes completed24 observations with no errors.','','The only substitution is the existing MoGParticlePrior constructor under a scoped runtime patch. Standardization and sigma calibration use the implementation in the exact source archive. Noise uses the original explicit training/evaluation RNG streams. Positive sigma therefore changes the realized sampling sequence as well as broadening each latent component. No source or threshold mutation occurred.','','| MoG setting | Task | HQ | Covariance error ≤.85 | Min eigen ≥.15 | Final | Final passing suffix |','|---|---|---:|---:|---:|---|---:|']
for row in rows:
    m=row['live']
    lines.append(f'| {row["card"]} | {row["task"]} | {m["hq"]:.4f} | {m["component_covariance_error"]:.4f} | {m["component_min_eigen_ratio"]:.4f} | {"PASS" if row["final_pass"] else "FAIL"} | {row["convergence"]["passing_suffix"]} |')
lines += ['', 'The closest unequal-mass spread result uses zero noise with standardized component means: covariance error.6728 passes but min-eigen.0828 fails. The lowest unequal-width covariance error is1.0003 using sigma_rel.025 without standardization; HQ.9875 and min-eigen.5583 pass, but the unchanged covariance bound remains failed. These are descriptive comparisons, not selected winners or evidence a larger untested MoG search cannot work.', '', 'Zero sigma without standardization is a semantic control: final live, EMA and all24 metric observations match the original atom-prior cosine runs exactly. Their original JSON files are included, with SHA256 recorded in baseline_atom_diagnostics.json.', '', 'Directly enumerated baseline particle outputs explain an observed failure: unequal_mass has actual assigned atom counts[131,81,38,6], with HQ counts[124,77,37,4]. The rare mode is present; two of its six atoms are off-mode and its sample covariance error is16.713. Unequal_width has atom counts[46,84,65,61], HQ counts[43,82,62,61]; the narrowest component has three off-mode atoms and covariance error26.273. This is concrete baseline tail evidence, not a claim about every candidate. Full generated-center coordinates are retained for all16 runs. For positive noise these are component-mean outputs, not every possible generated output.', '', 'Files: [protocol and exact cards](protocol.json), [full summary](summary.json), [scoped substitution source](run_mog.py), [numerical source archive](source.tar.gz), [baseline parity and atom evidence](baseline_atom_diagnostics.json), [log](progress.log). Compressed per-episode files preserve original JSON bytes; archive_manifest.json records hashes. No tracked repository files changed.']
(out/'README.md').write_text('\n'.join(lines)+'\n')
index={};compressed=out/'json_gz';compressed.mkdir(exist_ok=False)
for src in sorted(out.glob('*.json')):
    data=src.read_bytes();dest=compressed/(src.name+'.gz');dest.write_bytes(gzip.compress(data,mtime=0))
    index[str(dest.relative_to(out))]={'original_sha256':hashlib.sha256(data).hexdigest(),'gzip_sha256':hashlib.sha256(dest.read_bytes()).hexdigest()}
for src in list(out.glob('*.py'))+list(out.glob('reference_original*.json.gz'))+[out/'source.tar.gz',out/'README.md',out/'progress.log']:
    index[src.name]={'sha256':hashlib.sha256(src.read_bytes()).hexdigest()}
(out/'archive_manifest.json').write_text(json.dumps(index,indent=2)+'\n')
print('Packaged',len(rows),'episodes;',sum(r['seconds'] for r in rows),'elapsed episode seconds')
